# Generated by Django 4.2.19 on 2026-08-24 13:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("library_sample_shared", "0016_organism_label_organism_yaml_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indexpair",
            name="char_coord",
            field=models.CharField(
                max_length=1,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[A-Z]$", "Only capital letters characters are allowed."
                    )
                ],
                verbose_name="Character Coordinate",
            ),
        ),
    ]
