# Generated by Django 4.2.19 on 2026-09-15 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("flowcell", "0008_remove_flowcell_index1_cycles_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SequencingProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "archived",
                    models.BooleanField(default=False, verbose_name="Archived"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="flowcell",
            name="sequencing_provider_quote_id",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Sequencing Provider Quote ID"
            ),
        ),
        migrations.AlterField(
            model_name="flowcell",
            name="flowcell_id",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Flowcell ID"
            ),
        ),
        migrations.AddConstraint(
            model_name="flowcell",
            constraint=models.UniqueConstraint(
                condition=models.Q(("flowcell_id", ""), _negated=True),
                fields=("flowcell_id",),
                name="unique_flowcell_id_non_empty",
                violation_error_message="Flowcell ID must be unique when provided.",
            ),
        ),
        migrations.AddField(
            model_name="flowcell",
            name="sequencing_provider",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="flowcell.sequencingprovider",
                verbose_name="Sequencing Provider",
            ),
        ),
    ]
