# Generated by Django 4.2.19 on 2026-09-15 16:03

import django.db.models.deletion
from django.db import migrations, models


def normalize_sample_sheet_to_lane_list(sample_sheet):
    if sample_sheet is None:
        return None
    if isinstance(sample_sheet, list):
        return sample_sheet
    if isinstance(sample_sheet, dict):
        normalized = dict(sample_sheet)
        normalized.setdefault("lane", 1)
        return [normalized]
    return sample_sheet


def unwrap_sample_sheet_from_lane_list(sample_sheet):
    if isinstance(sample_sheet, list) and len(sample_sheet) == 1:
        lane_payload = sample_sheet[0]
        if isinstance(lane_payload, dict):
            unwrapped = dict(lane_payload)
            unwrapped.pop("lane", None)
            return unwrapped
    return sample_sheet


def create_internal_provider_and_assign(apps, schema_editor):
    SequencingProvider = apps.get_model("flowcell", "SequencingProvider")
    Flowcell = apps.get_model("flowcell", "Flowcell")

    provider, _ = SequencingProvider.objects.get_or_create(name="Internal")
    Flowcell.objects.filter(sequencing_provider__isnull=True).update(
        sequencing_provider=provider
    )

    for flowcell in Flowcell.objects.all():
        normalized = normalize_sample_sheet_to_lane_list(flowcell.sample_sheet)
        if normalized != flowcell.sample_sheet:
            flowcell.sample_sheet = normalized
            flowcell.save(update_fields=["sample_sheet"])


def reverse_internal_provider_assignment(apps, schema_editor):
    Flowcell = apps.get_model("flowcell", "Flowcell")
    SequencingProvider = apps.get_model("flowcell", "SequencingProvider")

    provider = SequencingProvider.objects.filter(name="Internal").first()
    if provider is None:
        return

    for flowcell in Flowcell.objects.filter(sequencing_provider=provider):
        unwrapped = unwrap_sample_sheet_from_lane_list(flowcell.sample_sheet)
        if unwrapped != flowcell.sample_sheet:
            flowcell.sample_sheet = unwrapped
            flowcell.save(update_fields=["sample_sheet"])

    Flowcell.objects.filter(sequencing_provider=provider).update(
        sequencing_provider=None
    )
    provider.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("flowcell", "0008_remove_flowcell_index1_cycles_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SequencingProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "archived",
                    models.BooleanField(default=False, verbose_name="Archived"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="flowcell",
            name="sequencing_provider_quote_id",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Sequencing Provider Quote ID"
            ),
        ),
        migrations.AlterField(
            model_name="flowcell",
            name="flowcell_id",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Flowcell ID"
            ),
        ),
        migrations.AddConstraint(
            model_name="flowcell",
            constraint=models.UniqueConstraint(
                condition=models.Q(("flowcell_id", ""), _negated=True),
                fields=("flowcell_id",),
                name="unique_flowcell_id_non_empty",
                violation_error_message="Flowcell ID must be unique when provided.",
            ),
        ),
        migrations.AddField(
            model_name="flowcell",
            name="sequencing_provider",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="flowcell.sequencingprovider",
                verbose_name="Sequencing Provider",
            ),
        ),
        migrations.RunPython(
            create_internal_provider_and_assign,
            reverse_internal_provider_assignment,
        ),
    ]
